export const QUERY_KEY = {
  StyleProduct: "StyleProduct",
  CompanyProduct: "CompanyProduct",
  SizeProduct: "SizeProduct",
  GroupProduct: "GroupProduct",
  Product: "Product",
  SaleProduct: "SaleProduct",
  TypeProduct: "TypeProduct",
  Categories: "Categories",
  Banner: "banner",
  user: "user",
  home: "Home",
  detailProduct: "detailProduct",
  searchPr: "searchPr",
  profile: "profile",
};
